### ISSUE TITLE
how to install capstone into IDA pro ？

### ISSUE THREAD

**Issue by shiwanghua** [Learner0x5a/kTrans-release#2]

**Comment by shiwanghua** [comment]
or how to change the python interpreter？

**Comment by Learner0x5a** [comment]
> or how to change the python interpreter？

Use idapyswitch under your idapro path.

**Comment by shiwanghua** [comment]
install by python3 pip 

copy the capstone dir to "...IDA_7\python27\Lib\site-packages\"

...IDA_7\python27\Lib\site-packages\capstone
